# Data Ingestion Related Configuration

artifacts_source: artifacts # executing the pipeline will create an artifacts folder, which would contain the artifacts related to different parts of the data science project (data ingestion, data validation, etc.)

data_ingestion:
  root_directory: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  local_data: artifacts/data_ingestion/data.zip
  unzip_directory: artifacts/data_ingestion # unzip and store it in the data_ingestion product


data_validation:
  root_directory: artifacts/data_validation
  unzip_data_directory: artifacts/data_ingestion/winequality-red.csv
  status_file: artifacts/data_validation/status.txt #validation of data. if data is correct, return true, else false
    #We will do schema validation

data_transformation:
  root_directory: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  root_directory: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  


